const STORE_TYPE = "search";

export const SEARCH_REQUEST = `${STORE_TYPE}/SEARCH_REQUEST`;
export const SEARCH_SUCCESS = `${STORE_TYPE}/SEARCH_SUCCESS`;
export const SEARCH_FAILURE = `${STORE_TYPE}/SEARCH_FAILURE`;